
create table Country
(
    CountryId int not null,
    CountryCode char(2) not null,
    CountryName varchar(100) not null,

    primary key(CountryId)
);

insert into Country (CountryCode, CountryName) values ('AF', 'Afghanistan');
insert into Country (CountryCode, CountryName) values ('AL', 'Albania');
insert into Country (CountryCode, CountryName) values ('DZ', 'Algeria');
insert into Country (CountryCode, CountryName) values ('AS', 'American Samoa');
insert into Country (CountryCode, CountryName) values ('AD', 'Andorra');
insert into Country (CountryCode, CountryName) values ('AO', 'Angola');
insert into Country (CountryCode, CountryName) values ('AI', 'Anguilla');
insert into Country (CountryCode, CountryName) values ('AQ', 'Antarctica');
insert into Country (CountryCode, CountryName) values ('AG', 'Antigua and Barbuda');
insert into Country (CountryCode, CountryName) values ('AR', 'Argentina');
insert into Country (CountryCode, CountryName) values ('AM', 'Armenia');
insert into Country (CountryCode, CountryName) values ('AW', 'Aruba');
insert into Country (CountryCode, CountryName) values ('AU', 'Australia');
insert into Country (CountryCode, CountryName) values ('AT', 'Austria');
insert into Country (CountryCode, CountryName) values ('AZ', 'Azerbaijan');
insert into Country (CountryCode, CountryName) values ('BS', 'Bahamas');
insert into Country (CountryCode, CountryName) values ('BH', 'Bahrain');
insert into Country (CountryCode, CountryName) values ('BD', 'Bangladesh');
insert into Country (CountryCode, CountryName) values ('BB', 'Barbados');
insert into Country (CountryCode, CountryName) values ('BY', 'Belarus');
insert into Country (CountryCode, CountryName) values ('BE', 'Belgium');
insert into Country (CountryCode, CountryName) values ('BZ', 'Belize');
insert into Country (CountryCode, CountryName) values ('BJ', 'Benin');
insert into Country (CountryCode, CountryName) values ('BM', 'Bermuda');
insert into Country (CountryCode, CountryName) values ('BT', 'Bhutan');
insert into Country (CountryCode, CountryName) values ('BO', 'Bolivia');
insert into Country (CountryCode, CountryName) values ('BA', 'Bosnia and Herzegovina');
insert into Country (CountryCode, CountryName) values ('BW', 'Botswana');
insert into Country (CountryCode, CountryName) values ('BV', 'Bouvet Island');
insert into Country (CountryCode, CountryName) values ('BR', 'Brazil');
insert into Country (CountryCode, CountryName) values ('IO', 'British Indian Ocean Territory');
insert into Country (CountryCode, CountryName) values ('BN', 'Brunei');
insert into Country (CountryCode, CountryName) values ('BG', 'Bulgaria');
insert into Country (CountryCode, CountryName) values ('BF', 'Burkina Faso');
insert into Country (CountryCode, CountryName) values ('BI', 'Burundi');
insert into Country (CountryCode, CountryName) values ('KH', 'Cambodia');
insert into Country (CountryCode, CountryName) values ('CM', 'Cameroon');
insert into Country (CountryCode, CountryName) values ('CA', 'Canada');
insert into Country (CountryCode, CountryName) values ('CV', 'Cape Verde');
insert into Country (CountryCode, CountryName) values ('KY', 'Cayman Islands');
insert into Country (CountryCode, CountryName) values ('CF', 'Central African Republic');
insert into Country (CountryCode, CountryName) values ('TD', 'Chad');
insert into Country (CountryCode, CountryName) values ('CL', 'Chile');
insert into Country (CountryCode, CountryName) values ('CN', 'China');
insert into Country (CountryCode, CountryName) values ('CX', 'Christmas Island');
insert into Country (CountryCode, CountryName) values ('CC', 'Cocos (Keeling) Islands');
insert into Country (CountryCode, CountryName) values ('CO', 'Colombia');
insert into Country (CountryCode, CountryName) values ('KM', 'Comoros');
insert into Country (CountryCode, CountryName) values ('CG', 'Congo');
insert into Country (CountryCode, CountryName) values ('CD', 'Congo, The Democratic Republic of the');
insert into Country (CountryCode, CountryName) values ('CK', 'Cook Islands');
insert into Country (CountryCode, CountryName) values ('CR', 'Costa Rica');
insert into Country (CountryCode, CountryName) values ('CI', 'Cote d''Ivoire');
insert into Country (CountryCode, CountryName) values ('HR', 'Croatia');
insert into Country (CountryCode, CountryName) values ('CU', 'Cuba');
insert into Country (CountryCode, CountryName) values ('CY', 'Cyprus');
insert into Country (CountryCode, CountryName) values ('CZ', 'Czech Republic');
insert into Country (CountryCode, CountryName) values ('DK', 'Denmark');
insert into Country (CountryCode, CountryName) values ('DJ', 'Djibouti');
insert into Country (CountryCode, CountryName) values ('DM', 'Dominica');
insert into Country (CountryCode, CountryName) values ('DO', 'Dominican Republic');
insert into Country (CountryCode, CountryName) values ('TP', 'East Timor');
insert into Country (CountryCode, CountryName) values ('EC', 'Ecuador');
insert into Country (CountryCode, CountryName) values ('EG', 'Egypt');
insert into Country (CountryCode, CountryName) values ('SV', 'El Salvador');
insert into Country (CountryCode, CountryName) values ('GQ', 'Equatorial Guinea');
insert into Country (CountryCode, CountryName) values ('ER', 'Eritrea');
insert into Country (CountryCode, CountryName) values ('EE', 'Estonia');
insert into Country (CountryCode, CountryName) values ('ET', 'Ethiopia');
insert into Country (CountryCode, CountryName) values ('FK', 'Falkland Islands');
insert into Country (CountryCode, CountryName) values ('FO', 'Faroe Islands');
insert into Country (CountryCode, CountryName) values ('FJ', 'Fiji Islands');
insert into Country (CountryCode, CountryName) values ('FI', 'Finland');
insert into Country (CountryCode, CountryName) values ('FR', 'France');
insert into Country (CountryCode, CountryName) values ('GF', 'French Guiana');
insert into Country (CountryCode, CountryName) values ('PF', 'French Polynesia');
insert into Country (CountryCode, CountryName) values ('TF', 'French Southern territories');
insert into Country (CountryCode, CountryName) values ('GA', 'Gabon');
insert into Country (CountryCode, CountryName) values ('GM', 'Gambia');
insert into Country (CountryCode, CountryName) values ('GE', 'Georgia');
insert into Country (CountryCode, CountryName) values ('DE', 'Germany');
insert into Country (CountryCode, CountryName) values ('GH', 'Ghana');
insert into Country (CountryCode, CountryName) values ('GI', 'Gibraltar');
insert into Country (CountryCode, CountryName) values ('GR', 'Greece');
insert into Country (CountryCode, CountryName) values ('GL', 'Greenland');
insert into Country (CountryCode, CountryName) values ('GD', 'Grenada');
insert into Country (CountryCode, CountryName) values ('GP', 'Guadeloupe');
insert into Country (CountryCode, CountryName) values ('GU', 'Guam');
insert into Country (CountryCode, CountryName) values ('GT', 'Guatemala');
insert into Country (CountryCode, CountryName) values ('GN', 'Guinea');
insert into Country (CountryCode, CountryName) values ('GW', 'Guinea-Bissau');
insert into Country (CountryCode, CountryName) values ('GY', 'Guyana');
insert into Country (CountryCode, CountryName) values ('HT', 'Haiti');
insert into Country (CountryCode, CountryName) values ('HM', 'Heard Island and McDonald Islands');
insert into Country (CountryCode, CountryName) values ('VA', 'Holy See (Vatican City State)');
insert into Country (CountryCode, CountryName) values ('HN', 'Honduras');
insert into Country (CountryCode, CountryName) values ('HK', 'Hong Kong');
insert into Country (CountryCode, CountryName) values ('HU', 'Hungary');
insert into Country (CountryCode, CountryName) values ('IS', 'Iceland');
insert into Country (CountryCode, CountryName) values ('IN', 'India');
insert into Country (CountryCode, CountryName) values ('ID', 'Indonesia');
insert into Country (CountryCode, CountryName) values ('IR', 'Iran');
insert into Country (CountryCode, CountryName) values ('IQ', 'Iraq');
insert into Country (CountryCode, CountryName) values ('IE', 'Ireland');
insert into Country (CountryCode, CountryName) values ('IL', 'Israel');
insert into Country (CountryCode, CountryName) values ('IT', 'Italy');
insert into Country (CountryCode, CountryName) values ('JM', 'Jamaica');
insert into Country (CountryCode, CountryName) values ('JP', 'Japan');
insert into Country (CountryCode, CountryName) values ('JO', 'Jordan');
insert into Country (CountryCode, CountryName) values ('KZ', 'Kazakstan');
insert into Country (CountryCode, CountryName) values ('KE', 'Kenya');
insert into Country (CountryCode, CountryName) values ('KI', 'Kiribati');
insert into Country (CountryCode, CountryName) values ('KW', 'Kuwait');
insert into Country (CountryCode, CountryName) values ('KG', 'Kyrgyzstan');
insert into Country (CountryCode, CountryName) values ('LA', 'Laos');
insert into Country (CountryCode, CountryName) values ('LV', 'Latvia');
insert into Country (CountryCode, CountryName) values ('LB', 'Lebanon');
insert into Country (CountryCode, CountryName) values ('LS', 'Lesotho');
insert into Country (CountryCode, CountryName) values ('LR', 'Liberia');
insert into Country (CountryCode, CountryName) values ('LY', 'Libyan Arab Jamahiriya');
insert into Country (CountryCode, CountryName) values ('LI', 'Liechtenstein');
insert into Country (CountryCode, CountryName) values ('LT', 'Lithuania');
insert into Country (CountryCode, CountryName) values ('LU', 'Luxembourg');
insert into Country (CountryCode, CountryName) values ('MO', 'Macao');
insert into Country (CountryCode, CountryName) values ('MK', 'Macedonia');
insert into Country (CountryCode, CountryName) values ('MG', 'Madagascar');
insert into Country (CountryCode, CountryName) values ('MW', 'Malawi');
insert into Country (CountryCode, CountryName) values ('MY', 'Malaysia');
insert into Country (CountryCode, CountryName) values ('MV', 'Maldives');
insert into Country (CountryCode, CountryName) values ('ML', 'Mali');
insert into Country (CountryCode, CountryName) values ('MT', 'Malta');
insert into Country (CountryCode, CountryName) values ('MH', 'Marshall Islands');
insert into Country (CountryCode, CountryName) values ('MQ', 'Martinique');
insert into Country (CountryCode, CountryName) values ('MR', 'Mauritania');
insert into Country (CountryCode, CountryName) values ('MU', 'Mauritius');
insert into Country (CountryCode, CountryName) values ('YT', 'Mayotte');
insert into Country (CountryCode, CountryName) values ('MX', 'Mexico');
insert into Country (CountryCode, CountryName) values ('FM', 'Micronesia, Federated States of');
insert into Country (CountryCode, CountryName) values ('MD', 'Moldova');
insert into Country (CountryCode, CountryName) values ('MC', 'Monaco');
insert into Country (CountryCode, CountryName) values ('MN', 'Mongolia');
insert into Country (CountryCode, CountryName) values ('MS', 'Montserrat');
insert into Country (CountryCode, CountryName) values ('MA', 'Morocco');
insert into Country (CountryCode, CountryName) values ('MZ', 'Mozambique');
insert into Country (CountryCode, CountryName) values ('MM', 'Myanmar');
insert into Country (CountryCode, CountryName) values ('NA', 'Namibia');
insert into Country (CountryCode, CountryName) values ('NR', 'Nauru');
insert into Country (CountryCode, CountryName) values ('NP', 'Nepal');
insert into Country (CountryCode, CountryName) values ('NL', 'Netherlands');
insert into Country (CountryCode, CountryName) values ('AN', 'Netherlands Antilles');
insert into Country (CountryCode, CountryName) values ('NC', 'New Caledonia');
insert into Country (CountryCode, CountryName) values ('NZ', 'New Zealand');
insert into Country (CountryCode, CountryName) values ('NI', 'Nicaragua');
insert into Country (CountryCode, CountryName) values ('NE', 'Niger');
insert into Country (CountryCode, CountryName) values ('NG', 'Nigeria');
insert into Country (CountryCode, CountryName) values ('NU', 'Niue');
insert into Country (CountryCode, CountryName) values ('NF', 'Norfolk Island');
insert into Country (CountryCode, CountryName) values ('KP', 'North Korea');
insert into Country (CountryCode, CountryName) values ('MP', 'Northern Mariana Islands');
insert into Country (CountryCode, CountryName) values ('NO', 'Norway');
insert into Country (CountryCode, CountryName) values ('OM', 'Oman');
insert into Country (CountryCode, CountryName) values ('PK', 'Pakistan');
insert into Country (CountryCode, CountryName) values ('PW', 'Palau');
insert into Country (CountryCode, CountryName) values ('PS', 'Palestine');
insert into Country (CountryCode, CountryName) values ('PA', 'Panama');
insert into Country (CountryCode, CountryName) values ('PG', 'Papua New Guinea');
insert into Country (CountryCode, CountryName) values ('PY', 'Paraguay');
insert into Country (CountryCode, CountryName) values ('PE', 'Peru');
insert into Country (CountryCode, CountryName) values ('PH', 'Philippines');
insert into Country (CountryCode, CountryName) values ('PN', 'Pitcairn');
insert into Country (CountryCode, CountryName) values ('PL', 'Poland');
insert into Country (CountryCode, CountryName) values ('PT', 'Portugal');
insert into Country (CountryCode, CountryName) values ('PR', 'Puerto Rico');
insert into Country (CountryCode, CountryName) values ('QA', 'Qatar');
insert into Country (CountryCode, CountryName) values ('RE', 'Reunion');
insert into Country (CountryCode, CountryName) values ('RO', 'Romania');
insert into Country (CountryCode, CountryName) values ('RU', 'Russian Federation');
insert into Country (CountryCode, CountryName) values ('RW', 'Rwanda');
insert into Country (CountryCode, CountryName) values ('SH', 'Saint Helena');
insert into Country (CountryCode, CountryName) values ('KN', 'Saint Kitts and Nevis');
insert into Country (CountryCode, CountryName) values ('LC', 'Saint Lucia');
insert into Country (CountryCode, CountryName) values ('PM', 'Saint Pierre and Miquelon');
insert into Country (CountryCode, CountryName) values ('VC', 'Saint Vincent and the Grenadines');
insert into Country (CountryCode, CountryName) values ('WS', 'Samoa');
insert into Country (CountryCode, CountryName) values ('SM', 'San Marino');
insert into Country (CountryCode, CountryName) values ('ST', 'Sao Tome and Principe');
insert into Country (CountryCode, CountryName) values ('SA', 'Saudi Arabia');
insert into Country (CountryCode, CountryName) values ('SN', 'Senegal');
insert into Country (CountryCode, CountryName) values ('SC', 'Seychelles');
insert into Country (CountryCode, CountryName) values ('SL', 'Sierra Leone');
insert into Country (CountryCode, CountryName) values ('SG', 'Singapore');
insert into Country (CountryCode, CountryName) values ('SK', 'Slovakia');
insert into Country (CountryCode, CountryName) values ('SI', 'Slovenia');
insert into Country (CountryCode, CountryName) values ('SB', 'Solomon Islands');
insert into Country (CountryCode, CountryName) values ('SO', 'Somalia');
insert into Country (CountryCode, CountryName) values ('ZA', 'South Africa');
insert into Country (CountryCode, CountryName) values ('GS', 'South Georgia and the South Sandwich Islands');
insert into Country (CountryCode, CountryName) values ('KR', 'South Korea');
insert into Country (CountryCode, CountryName) values ('ES', 'Spain');
insert into Country (CountryCode, CountryName) values ('LK', 'Sri Lanka');
insert into Country (CountryCode, CountryName) values ('SD', 'Sudan');
insert into Country (CountryCode, CountryName) values ('SR', 'Suriname');
insert into Country (CountryCode, CountryName) values ('SJ', 'Svalbard and Jan Mayen');
insert into Country (CountryCode, CountryName) values ('SZ', 'Swaziland');
insert into Country (CountryCode, CountryName) values ('SE', 'Sweden');
insert into Country (CountryCode, CountryName) values ('CH', 'Switzerland');
insert into Country (CountryCode, CountryName) values ('SY', 'Syria');
insert into Country (CountryCode, CountryName) values ('TW', 'Taiwan');
insert into Country (CountryCode, CountryName) values ('TJ', 'Tajikistan');
insert into Country (CountryCode, CountryName) values ('TZ', 'Tanzania');
insert into Country (CountryCode, CountryName) values ('TH', 'Thailand');
insert into Country (CountryCode, CountryName) values ('TG', 'Togo');
insert into Country (CountryCode, CountryName) values ('TK', 'Tokelau');
insert into Country (CountryCode, CountryName) values ('TO', 'Tonga');
insert into Country (CountryCode, CountryName) values ('TT', 'Trinidad and Tobago');
insert into Country (CountryCode, CountryName) values ('TN', 'Tunisia');
insert into Country (CountryCode, CountryName) values ('TR', 'Turkey');
insert into Country (CountryCode, CountryName) values ('TM', 'Turkmenistan');
insert into Country (CountryCode, CountryName) values ('TC', 'Turks and Caicos Islands');
insert into Country (CountryCode, CountryName) values ('TV', 'Tuvalu');
insert into Country (CountryCode, CountryName) values ('UG', 'Uganda');
insert into Country (CountryCode, CountryName) values ('UA', 'Ukraine');
insert into Country (CountryCode, CountryName) values ('AE', 'United Arab Emirates');
insert into Country (CountryCode, CountryName) values ('GB', 'United Kingdom');
insert into Country (CountryCode, CountryName) values ('US', 'United States');
insert into Country (CountryCode, CountryName) values ('UM', 'United States Minor Outlying Islands');
insert into Country (CountryCode, CountryName) values ('UY', 'Uruguay');
insert into Country (CountryCode, CountryName) values ('UZ', 'Uzbekistan');
insert into Country (CountryCode, CountryName) values ('VU', 'Vanuatu');
insert into Country (CountryCode, CountryName) values ('VE', 'Venezuela');
insert into Country (CountryCode, CountryName) values ('VN', 'Vietnam');
insert into Country (CountryCode, CountryName) values ('VG', 'Virgin Islands, British');
insert into Country (CountryCode, CountryName) values ('VI', 'Virgin Islands, U.S.');
insert into Country (CountryCode, CountryName) values ('WF', 'Wallis and Futuna');
insert into Country (CountryCode, CountryName) values ('EH', 'Western Sahara');
insert into Country (CountryCode, CountryName) values ('YE', 'Yemen');
insert into Country (CountryCode, CountryName) values ('YU', 'Yugoslavia');
insert into Country (CountryCode, CountryName) values ('ZM', 'Zambia');
insert into Country (CountryCode, CountryName) values ('ZW', 'Zimbabwe');

