
create table Country
(
    CountryId smallint not null,
    CountryCode char(2) not null,
    CountryName varchar(100) not null,

    primary key(CountryId)
);

insert into Country (CountryId, CountryCode, CountryName) values (1, 'AF', 'Afghanistan');
insert into Country (CountryId, CountryCode, CountryName) values (2, 'AL', 'Albania');
insert into Country (CountryId, CountryCode, CountryName) values (3, 'DZ', 'Algeria');
insert into Country (CountryId, CountryCode, CountryName) values (4, 'AS', 'American Samoa');
insert into Country (CountryId, CountryCode, CountryName) values (5, 'AD', 'Andorra');
insert into Country (CountryId, CountryCode, CountryName) values (6, 'AO', 'Angola');
insert into Country (CountryId, CountryCode, CountryName) values (7, 'AI', 'Anguilla');
insert into Country (CountryId, CountryCode, CountryName) values (8, 'AQ', 'Antarctica');
insert into Country (CountryId, CountryCode, CountryName) values (9, 'AG', 'Antigua and Barbuda');
insert into Country (CountryId, CountryCode, CountryName) values (10, 'AR', 'Argentina');
insert into Country (CountryId, CountryCode, CountryName) values (11, 'AM', 'Armenia');
insert into Country (CountryId, CountryCode, CountryName) values (12, 'AW', 'Aruba');
insert into Country (CountryId, CountryCode, CountryName) values (13, 'AU', 'Australia');
insert into Country (CountryId, CountryCode, CountryName) values (14, 'AT', 'Austria');
insert into Country (CountryId, CountryCode, CountryName) values (15, 'AZ', 'Azerbaijan');
insert into Country (CountryId, CountryCode, CountryName) values (16, 'BS', 'Bahamas');
insert into Country (CountryId, CountryCode, CountryName) values (17, 'BH', 'Bahrain');
insert into Country (CountryId, CountryCode, CountryName) values (18, 'BD', 'Bangladesh');
insert into Country (CountryId, CountryCode, CountryName) values (19, 'BB', 'Barbados');
insert into Country (CountryId, CountryCode, CountryName) values (20, 'BY', 'Belarus');
insert into Country (CountryId, CountryCode, CountryName) values (21, 'BE', 'Belgium');
insert into Country (CountryId, CountryCode, CountryName) values (22, 'BZ', 'Belize');
insert into Country (CountryId, CountryCode, CountryName) values (23, 'BJ', 'Benin');
insert into Country (CountryId, CountryCode, CountryName) values (24, 'BM', 'Bermuda');
insert into Country (CountryId, CountryCode, CountryName) values (25, 'BT', 'Bhutan');
insert into Country (CountryId, CountryCode, CountryName) values (26, 'BO', 'Bolivia');
insert into Country (CountryId, CountryCode, CountryName) values (27, 'BA', 'Bosnia and Herzegovina');
insert into Country (CountryId, CountryCode, CountryName) values (28, 'BW', 'Botswana');
insert into Country (CountryId, CountryCode, CountryName) values (29, 'BV', 'Bouvet Island');
insert into Country (CountryId, CountryCode, CountryName) values (30, 'BR', 'Brazil');
insert into Country (CountryId, CountryCode, CountryName) values (31, 'IO', 'British Indian Ocean Territory');
insert into Country (CountryId, CountryCode, CountryName) values (32, 'BN', 'Brunei');
insert into Country (CountryId, CountryCode, CountryName) values (33, 'BG', 'Bulgaria');
insert into Country (CountryId, CountryCode, CountryName) values (34, 'BF', 'Burkina Faso');
insert into Country (CountryId, CountryCode, CountryName) values (35, 'BI', 'Burundi');
insert into Country (CountryId, CountryCode, CountryName) values (36, 'KH', 'Cambodia');
insert into Country (CountryId, CountryCode, CountryName) values (37, 'CM', 'Cameroon');
insert into Country (CountryId, CountryCode, CountryName) values (38, 'CA', 'Canada');
insert into Country (CountryId, CountryCode, CountryName) values (39, 'CV', 'Cape Verde');
insert into Country (CountryId, CountryCode, CountryName) values (40, 'KY', 'Cayman Islands');
insert into Country (CountryId, CountryCode, CountryName) values (41, 'CF', 'Central African Republic');
insert into Country (CountryId, CountryCode, CountryName) values (42, 'TD', 'Chad');
insert into Country (CountryId, CountryCode, CountryName) values (43, 'CL', 'Chile');
insert into Country (CountryId, CountryCode, CountryName) values (44, 'CN', 'China');
insert into Country (CountryId, CountryCode, CountryName) values (45, 'CX', 'Christmas Island');
insert into Country (CountryId, CountryCode, CountryName) values (46, 'CC', 'Cocos (Keeling) Islands');
insert into Country (CountryId, CountryCode, CountryName) values (47, 'CO', 'Colombia');
insert into Country (CountryId, CountryCode, CountryName) values (48, 'KM', 'Comoros');
insert into Country (CountryId, CountryCode, CountryName) values (49, 'CG', 'Congo');
insert into Country (CountryId, CountryCode, CountryName) values (50, 'CD', 'Congo, The Democratic Republic of the');
insert into Country (CountryId, CountryCode, CountryName) values (51, 'CK', 'Cook Islands');
insert into Country (CountryId, CountryCode, CountryName) values (52, 'CR', 'Costa Rica');
insert into Country (CountryId, CountryCode, CountryName) values (53, 'CI', 'Cote d''Ivoire');
insert into Country (CountryId, CountryCode, CountryName) values (54, 'HR', 'Croatia');
insert into Country (CountryId, CountryCode, CountryName) values (55, 'CU', 'Cuba');
insert into Country (CountryId, CountryCode, CountryName) values (56, 'CY', 'Cyprus');
insert into Country (CountryId, CountryCode, CountryName) values (57, 'CZ', 'Czech Republic');
insert into Country (CountryId, CountryCode, CountryName) values (58, 'DK', 'Denmark');
insert into Country (CountryId, CountryCode, CountryName) values (59, 'DJ', 'Djibouti');
insert into Country (CountryId, CountryCode, CountryName) values (60, 'DM', 'Dominica');
insert into Country (CountryId, CountryCode, CountryName) values (61, 'DO', 'Dominican Republic');
insert into Country (CountryId, CountryCode, CountryName) values (62, 'TP', 'East Timor');
insert into Country (CountryId, CountryCode, CountryName) values (63, 'EC', 'Ecuador');
insert into Country (CountryId, CountryCode, CountryName) values (64, 'EG', 'Egypt');
insert into Country (CountryId, CountryCode, CountryName) values (65, 'SV', 'El Salvador');
insert into Country (CountryId, CountryCode, CountryName) values (66, 'GQ', 'Equatorial Guinea');
insert into Country (CountryId, CountryCode, CountryName) values (67, 'ER', 'Eritrea');
insert into Country (CountryId, CountryCode, CountryName) values (68, 'EE', 'Estonia');
insert into Country (CountryId, CountryCode, CountryName) values (69, 'ET', 'Ethiopia');
insert into Country (CountryId, CountryCode, CountryName) values (70, 'FK', 'Falkland Islands');
insert into Country (CountryId, CountryCode, CountryName) values (71, 'FO', 'Faroe Islands');
insert into Country (CountryId, CountryCode, CountryName) values (72, 'FJ', 'Fiji Islands');
insert into Country (CountryId, CountryCode, CountryName) values (73, 'FI', 'Finland');
insert into Country (CountryId, CountryCode, CountryName) values (74, 'FR', 'France');
insert into Country (CountryId, CountryCode, CountryName) values (75, 'GF', 'French Guiana');
insert into Country (CountryId, CountryCode, CountryName) values (76, 'PF', 'French Polynesia');
insert into Country (CountryId, CountryCode, CountryName) values (77, 'TF', 'French Southern territories');
insert into Country (CountryId, CountryCode, CountryName) values (78, 'GA', 'Gabon');
insert into Country (CountryId, CountryCode, CountryName) values (79, 'GM', 'Gambia');
insert into Country (CountryId, CountryCode, CountryName) values (80, 'GE', 'Georgia');
insert into Country (CountryId, CountryCode, CountryName) values (81, 'DE', 'Germany');
insert into Country (CountryId, CountryCode, CountryName) values (82, 'GH', 'Ghana');
insert into Country (CountryId, CountryCode, CountryName) values (83, 'GI', 'Gibraltar');
insert into Country (CountryId, CountryCode, CountryName) values (84, 'GR', 'Greece');
insert into Country (CountryId, CountryCode, CountryName) values (85, 'GL', 'Greenland');
insert into Country (CountryId, CountryCode, CountryName) values (86, 'GD', 'Grenada');
insert into Country (CountryId, CountryCode, CountryName) values (87, 'GP', 'Guadeloupe');
insert into Country (CountryId, CountryCode, CountryName) values (88, 'GU', 'Guam');
insert into Country (CountryId, CountryCode, CountryName) values (89, 'GT', 'Guatemala');
insert into Country (CountryId, CountryCode, CountryName) values (90, 'GN', 'Guinea');
insert into Country (CountryId, CountryCode, CountryName) values (91, 'GW', 'Guinea-Bissau');
insert into Country (CountryId, CountryCode, CountryName) values (92, 'GY', 'Guyana');
insert into Country (CountryId, CountryCode, CountryName) values (93, 'HT', 'Haiti');
insert into Country (CountryId, CountryCode, CountryName) values (94, 'HM', 'Heard Island and McDonald Islands');
insert into Country (CountryId, CountryCode, CountryName) values (95, 'VA', 'Holy See (Vatican City State)');
insert into Country (CountryId, CountryCode, CountryName) values (96, 'HN', 'Honduras');
insert into Country (CountryId, CountryCode, CountryName) values (97, 'HK', 'Hong Kong');
insert into Country (CountryId, CountryCode, CountryName) values (98, 'HU', 'Hungary');
insert into Country (CountryId, CountryCode, CountryName) values (99, 'IS', 'Iceland');
insert into Country (CountryId, CountryCode, CountryName) values (100, 'IN', 'India');
insert into Country (CountryId, CountryCode, CountryName) values (101, 'ID', 'Indonesia');
insert into Country (CountryId, CountryCode, CountryName) values (102, 'IR', 'Iran');
insert into Country (CountryId, CountryCode, CountryName) values (103, 'IQ', 'Iraq');
insert into Country (CountryId, CountryCode, CountryName) values (104, 'IE', 'Ireland');
insert into Country (CountryId, CountryCode, CountryName) values (105, 'IL', 'Israel');
insert into Country (CountryId, CountryCode, CountryName) values (106, 'IT', 'Italy');
insert into Country (CountryId, CountryCode, CountryName) values (107, 'JM', 'Jamaica');
insert into Country (CountryId, CountryCode, CountryName) values (108, 'JP', 'Japan');
insert into Country (CountryId, CountryCode, CountryName) values (109, 'JO', 'Jordan');
insert into Country (CountryId, CountryCode, CountryName) values (110, 'KZ', 'Kazakstan');
insert into Country (CountryId, CountryCode, CountryName) values (111, 'KE', 'Kenya');
insert into Country (CountryId, CountryCode, CountryName) values (112, 'KI', 'Kiribati');
insert into Country (CountryId, CountryCode, CountryName) values (113, 'KW', 'Kuwait');
insert into Country (CountryId, CountryCode, CountryName) values (114, 'KG', 'Kyrgyzstan');
insert into Country (CountryId, CountryCode, CountryName) values (115, 'LA', 'Laos');
insert into Country (CountryId, CountryCode, CountryName) values (116, 'LV', 'Latvia');
insert into Country (CountryId, CountryCode, CountryName) values (117, 'LB', 'Lebanon');
insert into Country (CountryId, CountryCode, CountryName) values (118, 'LS', 'Lesotho');
insert into Country (CountryId, CountryCode, CountryName) values (119, 'LR', 'Liberia');
insert into Country (CountryId, CountryCode, CountryName) values (120, 'LY', 'Libyan Arab Jamahiriya');
insert into Country (CountryId, CountryCode, CountryName) values (121, 'LI', 'Liechtenstein');
insert into Country (CountryId, CountryCode, CountryName) values (122, 'LT', 'Lithuania');
insert into Country (CountryId, CountryCode, CountryName) values (123, 'LU', 'Luxembourg');
insert into Country (CountryId, CountryCode, CountryName) values (124, 'MO', 'Macao');
insert into Country (CountryId, CountryCode, CountryName) values (125, 'MK', 'Macedonia');
insert into Country (CountryId, CountryCode, CountryName) values (126, 'MG', 'Madagascar');
insert into Country (CountryId, CountryCode, CountryName) values (127, 'MW', 'Malawi');
insert into Country (CountryId, CountryCode, CountryName) values (128, 'MY', 'Malaysia');
insert into Country (CountryId, CountryCode, CountryName) values (129, 'MV', 'Maldives');
insert into Country (CountryId, CountryCode, CountryName) values (130, 'ML', 'Mali');
insert into Country (CountryId, CountryCode, CountryName) values (131, 'MT', 'Malta');
insert into Country (CountryId, CountryCode, CountryName) values (132, 'MH', 'Marshall Islands');
insert into Country (CountryId, CountryCode, CountryName) values (133, 'MQ', 'Martinique');
insert into Country (CountryId, CountryCode, CountryName) values (134, 'MR', 'Mauritania');
insert into Country (CountryId, CountryCode, CountryName) values (135, 'MU', 'Mauritius');
insert into Country (CountryId, CountryCode, CountryName) values (136, 'YT', 'Mayotte');
insert into Country (CountryId, CountryCode, CountryName) values (137, 'MX', 'Mexico');
insert into Country (CountryId, CountryCode, CountryName) values (138, 'FM', 'Micronesia, Federated States of');
insert into Country (CountryId, CountryCode, CountryName) values (139, 'MD', 'Moldova');
insert into Country (CountryId, CountryCode, CountryName) values (140, 'MC', 'Monaco');
insert into Country (CountryId, CountryCode, CountryName) values (141, 'MN', 'Mongolia');
insert into Country (CountryId, CountryCode, CountryName) values (142, 'MS', 'Montserrat');
insert into Country (CountryId, CountryCode, CountryName) values (143, 'MA', 'Morocco');
insert into Country (CountryId, CountryCode, CountryName) values (144, 'MZ', 'Mozambique');
insert into Country (CountryId, CountryCode, CountryName) values (145, 'MM', 'Myanmar');
insert into Country (CountryId, CountryCode, CountryName) values (146, 'NA', 'Namibia');
insert into Country (CountryId, CountryCode, CountryName) values (147, 'NR', 'Nauru');
insert into Country (CountryId, CountryCode, CountryName) values (148, 'NP', 'Nepal');
insert into Country (CountryId, CountryCode, CountryName) values (149, 'NL', 'Netherlands');
insert into Country (CountryId, CountryCode, CountryName) values (150, 'AN', 'Netherlands Antilles');
insert into Country (CountryId, CountryCode, CountryName) values (151, 'NC', 'New Caledonia');
insert into Country (CountryId, CountryCode, CountryName) values (152, 'NZ', 'New Zealand');
insert into Country (CountryId, CountryCode, CountryName) values (153, 'NI', 'Nicaragua');
insert into Country (CountryId, CountryCode, CountryName) values (154, 'NE', 'Niger');
insert into Country (CountryId, CountryCode, CountryName) values (155, 'NG', 'Nigeria');
insert into Country (CountryId, CountryCode, CountryName) values (156, 'NU', 'Niue');
insert into Country (CountryId, CountryCode, CountryName) values (157, 'NF', 'Norfolk Island');
insert into Country (CountryId, CountryCode, CountryName) values (158, 'KP', 'North Korea');
insert into Country (CountryId, CountryCode, CountryName) values (159, 'MP', 'Northern Mariana Islands');
insert into Country (CountryId, CountryCode, CountryName) values (160, 'NO', 'Norway');
insert into Country (CountryId, CountryCode, CountryName) values (161, 'OM', 'Oman');
insert into Country (CountryId, CountryCode, CountryName) values (162, 'PK', 'Pakistan');
insert into Country (CountryId, CountryCode, CountryName) values (163, 'PW', 'Palau');
insert into Country (CountryId, CountryCode, CountryName) values (164, 'PS', 'Palestine');
insert into Country (CountryId, CountryCode, CountryName) values (165, 'PA', 'Panama');
insert into Country (CountryId, CountryCode, CountryName) values (166, 'PG', 'Papua New Guinea');
insert into Country (CountryId, CountryCode, CountryName) values (167, 'PY', 'Paraguay');
insert into Country (CountryId, CountryCode, CountryName) values (168, 'PE', 'Peru');
insert into Country (CountryId, CountryCode, CountryName) values (169, 'PH', 'Philippines');
insert into Country (CountryId, CountryCode, CountryName) values (170, 'PN', 'Pitcairn');
insert into Country (CountryId, CountryCode, CountryName) values (171, 'PL', 'Poland');
insert into Country (CountryId, CountryCode, CountryName) values (172, 'PT', 'Portugal');
insert into Country (CountryId, CountryCode, CountryName) values (173, 'PR', 'Puerto Rico');
insert into Country (CountryId, CountryCode, CountryName) values (174, 'QA', 'Qatar');
insert into Country (CountryId, CountryCode, CountryName) values (175, 'RE', 'Reunion');
insert into Country (CountryId, CountryCode, CountryName) values (176, 'RO', 'Romania');
insert into Country (CountryId, CountryCode, CountryName) values (177, 'RU', 'Russian Federation');
insert into Country (CountryId, CountryCode, CountryName) values (178, 'RW', 'Rwanda');
insert into Country (CountryId, CountryCode, CountryName) values (179, 'SH', 'Saint Helena');
insert into Country (CountryId, CountryCode, CountryName) values (180, 'KN', 'Saint Kitts and Nevis');
insert into Country (CountryId, CountryCode, CountryName) values (181, 'LC', 'Saint Lucia');
insert into Country (CountryId, CountryCode, CountryName) values (182, 'PM', 'Saint Pierre and Miquelon');
insert into Country (CountryId, CountryCode, CountryName) values (183, 'VC', 'Saint Vincent and the Grenadines');
insert into Country (CountryId, CountryCode, CountryName) values (184, 'WS', 'Samoa');
insert into Country (CountryId, CountryCode, CountryName) values (185, 'SM', 'San Marino');
insert into Country (CountryId, CountryCode, CountryName) values (186, 'ST', 'Sao Tome and Principe');
insert into Country (CountryId, CountryCode, CountryName) values (187, 'SA', 'Saudi Arabia');
insert into Country (CountryId, CountryCode, CountryName) values (188, 'SN', 'Senegal');
insert into Country (CountryId, CountryCode, CountryName) values (189, 'SC', 'Seychelles');
insert into Country (CountryId, CountryCode, CountryName) values (190, 'SL', 'Sierra Leone');
insert into Country (CountryId, CountryCode, CountryName) values (191, 'SG', 'Singapore');
insert into Country (CountryId, CountryCode, CountryName) values (192, 'SK', 'Slovakia');
insert into Country (CountryId, CountryCode, CountryName) values (193, 'SI', 'Slovenia');
insert into Country (CountryId, CountryCode, CountryName) values (194, 'SB', 'Solomon Islands');
insert into Country (CountryId, CountryCode, CountryName) values (195, 'SO', 'Somalia');
insert into Country (CountryId, CountryCode, CountryName) values (196, 'ZA', 'South Africa');
insert into Country (CountryId, CountryCode, CountryName) values (197, 'GS', 'South Georgia and the South Sandwich Islands');
insert into Country (CountryId, CountryCode, CountryName) values (198, 'KR', 'South Korea');
insert into Country (CountryId, CountryCode, CountryName) values (199, 'ES', 'Spain');
insert into Country (CountryId, CountryCode, CountryName) values (200, 'LK', 'Sri Lanka');
insert into Country (CountryId, CountryCode, CountryName) values (201, 'SD', 'Sudan');
insert into Country (CountryId, CountryCode, CountryName) values (202, 'SR', 'Suriname');
insert into Country (CountryId, CountryCode, CountryName) values (203, 'SJ', 'Svalbard and Jan Mayen');
insert into Country (CountryId, CountryCode, CountryName) values (204, 'SZ', 'Swaziland');
insert into Country (CountryId, CountryCode, CountryName) values (205, 'SE', 'Sweden');
insert into Country (CountryId, CountryCode, CountryName) values (206, 'CH', 'Switzerland');
insert into Country (CountryId, CountryCode, CountryName) values (207, 'SY', 'Syria');
insert into Country (CountryId, CountryCode, CountryName) values (208, 'TW', 'Taiwan');
insert into Country (CountryId, CountryCode, CountryName) values (209, 'TJ', 'Tajikistan');
insert into Country (CountryId, CountryCode, CountryName) values (210, 'TZ', 'Tanzania');
insert into Country (CountryId, CountryCode, CountryName) values (211, 'TH', 'Thailand');
insert into Country (CountryId, CountryCode, CountryName) values (212, 'TG', 'Togo');
insert into Country (CountryId, CountryCode, CountryName) values (213, 'TK', 'Tokelau');
insert into Country (CountryId, CountryCode, CountryName) values (214, 'TO', 'Tonga');
insert into Country (CountryId, CountryCode, CountryName) values (215, 'TT', 'Trinidad and Tobago');
insert into Country (CountryId, CountryCode, CountryName) values (216, 'TN', 'Tunisia');
insert into Country (CountryId, CountryCode, CountryName) values (217, 'TR', 'Turkey');
insert into Country (CountryId, CountryCode, CountryName) values (218, 'TM', 'Turkmenistan');
insert into Country (CountryId, CountryCode, CountryName) values (219, 'TC', 'Turks and Caicos Islands');
insert into Country (CountryId, CountryCode, CountryName) values (220, 'TV', 'Tuvalu');
insert into Country (CountryId, CountryCode, CountryName) values (221, 'UG', 'Uganda');
insert into Country (CountryId, CountryCode, CountryName) values (222, 'UA', 'Ukraine');
insert into Country (CountryId, CountryCode, CountryName) values (223, 'AE', 'United Arab Emirates');
insert into Country (CountryId, CountryCode, CountryName) values (224, 'GB', 'United Kingdom');
insert into Country (CountryId, CountryCode, CountryName) values (225, 'US', 'United States');
insert into Country (CountryId, CountryCode, CountryName) values (226, 'UM', 'United States Minor Outlying Islands');
insert into Country (CountryId, CountryCode, CountryName) values (227, 'UY', 'Uruguay');
insert into Country (CountryId, CountryCode, CountryName) values (228, 'UZ', 'Uzbekistan');
insert into Country (CountryId, CountryCode, CountryName) values (229, 'VU', 'Vanuatu');
insert into Country (CountryId, CountryCode, CountryName) values (230, 'VE', 'Venezuela');
insert into Country (CountryId, CountryCode, CountryName) values (231, 'VN', 'Vietnam');
insert into Country (CountryId, CountryCode, CountryName) values (232, 'VG', 'Virgin Islands, British');
insert into Country (CountryId, CountryCode, CountryName) values (233, 'VI', 'Virgin Islands, U.S.');
insert into Country (CountryId, CountryCode, CountryName) values (234, 'WF', 'Wallis and Futuna');
insert into Country (CountryId, CountryCode, CountryName) values (235, 'EH', 'Western Sahara');
insert into Country (CountryId, CountryCode, CountryName) values (236, 'YE', 'Yemen');
insert into Country (CountryId, CountryCode, CountryName) values (237, 'YU', 'Yugoslavia');
insert into Country (CountryId, CountryCode, CountryName) values (238, 'ZM', 'Zambia');
insert into Country (CountryId, CountryCode, CountryName) values (239, 'ZW', 'Zimbabwe');

